plugins {
    id 'java'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

def flinkVersion = '1.19.0'

dependencies {
    implementation "org.apache.flink:flink-streaming-java:${flinkVersion}"
    implementation "org.apache.flink:flink-clients:${flinkVersion}"

    // Simple logging for local runs
    runtimeOnly 'org.slf4j:slf4j-simple:2.0.13'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.3'
}

test {
    useJUnitPlatform()
}

applicationDefaultJvmArgs = [
        // Tweak as needed for local runs
]
